# -*- coding: utf-8 -*-
"""2cdi1235.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14fz9jrxiGY8oAqzfirq_ysjUvEYjm9CA
"""

import requests
import json

def geocode(address, api_key):
    url = f"https://maps.googleapis.com/maps/api/geocode/json?address={address}&key={api_key}"
    response = requests.get(url)
    data = json.loads(response.text)

    if data['status'] == 'OK':
        results = data['results']
        for result in results:
            formatted_address = result['formatted_address']
            location = result['geometry']['location']
            latitude = location['lat']
            longitude = location['lng']
            print(f"Address: {formatted_address}")
            print(f"Latitude: {latitude}")
            print(f"Longitude: {longitude}")
            print("-----------------------")
    else:
        print(f"Geocoding failed. Status: {data['status']}")

# APIキーに置き換える
api_key = "YOUR KEY"

# テストアドレス
address = "1600 Amphitheatre Parkway, Mountain View, CA"

# テスト用のgeocode関数を呼び出す
geocode(address, api_key)